### ISSUE TITLE
Exchange causes segfault in config destructor

### ISSUE THREAD

**Issue by Am1GO** [zbackup/zbackup#79]
```
(gdb) bt f
#0  0x0806906d in Config::~Config (this=0xbf9bc9d4, __in_chrg=<value optimized out>) at /home/AmiGO/soft/sources/zbackup/config.cc:140
No locals.
#1  0x08078018 in main (argc=146498600, argv=0x8bb7be0) at /home/AmiGO/soft/sources/zbackup/zbackup.cc:386
        printHelp = <value optimized out>
        args = std::vector of length 3, capacity 4 = {0xbf9bde0d "export", 0xbf9bde14 "repos/1/", 0xbf9bde2d "repos/2/"}
        passwords = std::vector of length 2, capacity 2 = {"", ""}
        config = {
          runtime = {
            threads = 4, 
            cacheSize = 41943040, 
            exchange = std::bitset = {
              [0] = 1,
              [1] = 1,
              [2] = 1
            }
          }, 
          storable = 0x8bb8338, 
          keywords = 0x8bb978c, 
          cleanup_storable = true, 
          cleanup_keywords = true
        }
        __func__ = "main"
```

**Comment by Am1GO** [comment]
Fixed in 864cd575700c45aac496ec73b6c4aca3683e2f00
